[workspace]
resolver = "2"

members = [
  "timesman-bstore",
  "timesman-app",
  "timesman-server",
  "timesman-grpc",
  "timesman-tools",
  "timesman-type",
]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
