[package]
name = "timesman-type"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
uuid = { version = "1.10.0", features = ["v4", "serde"] }

[dev-dependencies]
serde_json = "1.0"
